---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: false
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
- Mail
- FaceTime
- Podcasts
- Mapas
- TV
- Numbers
- Pages
- Keynote
dockitems_persist:
- name: "Obsidian"
  path: "/Applications/Obsidian.app/"
  pos: 10
- name: "iTerm"
  path: "/Applications/iTerm.app/"
  pos: 14
- name: "WhatsApp"
  path: "/Applications/WhatsApp.app/"
  pos: 15
- name: "Money Pro"
  path: "/Applications/Money Pro.app/"
  pos: 16
- name: "Pixelmator Pro"
  path: "/Applications/Pixelmator Pro.app/"
  pos: 17

homebrew_installed_packages:
  - kubectx
  - kubernetes-cli
  - jq
  - tmux
  - starship
  - terraform
  - 

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  # - iterm2
  # - whatsapp
  # - 1password
  # - docker
  # - google-chrome
  # - visual-studio-code
  # - Obsidian
  # - Pixelmator pro
  # - Money Pro
  - font-fira-code

pip_packages:
  - name: virtualenv
    state: present

vscode_extensions:
  - hashicorp.terraform
  - jdinhlife.gruvbox
  - ms-azuretools.vscode-docker
  - ms-dotnettools.csharp
  - ms-kubernetes-tools.vscode-kubernetes-tools
  - ms-ossdata.vscode-postgresql
  - ms-python.python
  - ms-python.vscode-pylance
  - ms-python.isort
  - ms-toolsai.jupyter
  - ms-toolsai.jupyter-keymap
  - ms-toolsai.jupyter-renderers
  - ms-vscode-remote.remote-containers
  - ms-vscode-remote.remote-ssh
  - ms-vscode-remote.remote-ssh-edit
  - ms-vscode.cpptools
  - oderwat.indent-rainbow
  - redhat.vscode-yaml
  - catppuccin.catppuccin-vsc
  - esbenp.prettier-vscode
# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
