---
- name: Check that OMZSH path is present
  ansible.builtin.stat:
    path: '~/.oh-my-zsh'
  register: omzsh

- name: Install oh-my-zsh
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: omzsh.stat.exists

- name: Configure oh-my-zsh plugins
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    regexp: '^plugins'
    line: 'plugins=(git kubectl kube-ps1 macos oc)'

- name: User configuration
  ansible.builtin.blockinfile:
    path: ~/.zshrc
    block: |
      export PATH=$PATH:~/Library/Python/3.8/bin/
      export PATH=$PATH:/usr/local/bin/google-cloud-sdk/bin
      export PATH=$PATH:/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/
      export ANSIBLE_HOST_KEY_CHECKING=False
      PROMPT=$PROMPT'$(kube_ps1) '
      alias python="python3"
      alias pip="pip3"
