---
# Autohide the dock
- osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true
    state: present

# Do not display recent apps in the Dock
- osx_defaults:
    domain: com.apple.dock
    key: show-recents
    type: bool
    value: false
    state: present

# Save to disk (not to iCloud) by default
- osx_defaults:
    domain: NSGlobalDomain
    key: NSDocumentSaveNewDocumentsToCloud
    type: bool
    value: false
    state: present

# Disable smart quotes as they’re annoying when typing code
- osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticQuoteSubstitutionEnabled
    type: bool
    value: false
    state: present

# Disable smart dashes as they’re annoying when typing code
- osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticDashSubstitutionEnabled
    type: bool
    value: false
    state: present

# Disable auto-correct
- osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false
    state: present

# Save screenshots to Downloads folder.
- osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: "${HOME}/Downloads"
    state: present

# Disable shadow in screenshots
- osx_defaults:
    domain: com.apple.screencapture
    key: disable-shadow
    type: bool
    value: true
    state: present

# Set Desktop as the default location for new Finder windows
- osx_defaults:
    domain: com.apple.finder
    key: NewWindowTarget
    type: string
    value: "PfHm"
    state: present

- osx_defaults:
    domain: com.apple.finder
    key: NewWindowTargetPath
    type: string
    value: "file://${HOME}/"
    state: present

# Finder: show status bar
- osx_defaults:
    domain: com.apple.finder
    key: ShowStatusBar
    type: bool
    value: true
    state: present

# Finder: show path bar
- osx_defaults:
    domain: com.apple.finder
    key: ShowPathbar
    type: bool
    value: true
    state: present

# When performing a search, search the current folder by default
- osx_defaults:
    domain: com.apple.finder
    key: FXDefaultSearchScope
    type: string
    value: "SCcf"
    state: present

# Avoid creating .DS_Store files on network volumes
- osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true
    state: present

# Music notifications will not be displayed.
- osx_defaults:
    domain: com.apple.Music
    key: userWantsPlaybackNotifications
    type: bool
    value: false
    state: present
